export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const UPDATE_CATEGORIES  = "UPDATE_CATEGORIES";
export const DELETE_CATEGORY  = "DELETE_CATEGORY";

export const GET_NEWS  = "GET_NEWS";
export const CREATE_NEWS  = "CREATE_NEWS";
export const UPDATE_NEWS  = "UPDATE_NEWS";
export const DELETE_NEWS  = "DELETE_NEWS";
export const GET_NEWS_BY_ID  = "GET_NEWS_BY_ID";

export const GET_ROLES = "GET_ROLES";
export const CREATE_ROLE = "CREATE_ROLE";
export const UPDATE_ROLE = "UPDATE_ROLE";
export const DELETE_ROLE = "DELETE_ROLE";

export const GET_AUTHORS = "GET_AUTHORS";
export const CREATE_AUTHOR = "CREATE_AUTHOR";
export const UPDATE_AUTHOR = "UPDATE_AUTHOR";
export const DELETE_AUTHOR = "DELETE_AUTHOR";

export const GET_USERS = "GET_USERS";
export const CREATE_USER = "CREATE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const UPDATE_LOGGED_USER = "UPDATE_LOGGED_USER";

export const CREATE_MODIFICATION = "CREATE_MODIFICATION";
export const GET_MODIFICATIONS = "GET_MODIFICATIONS";
export const MARK_AS_READ = "MARK_AS_READ";
export const DELETE_USER_MODIFICATIONS = "DELETE_USER_MODIFICATIONS";

export const GET_COMMENTS = "GET_COMMENTS";
export const DELETE_COMMENT = "DELETE_COMMENT";

export const GET_ADS_LATERAL = "GET_ADS_LATERAL";
export const CREATE_ADS_LATERAL = "CREATE_ADS_LATERAL";
export const UPDATE_ADS_LATERAL = "UPDATE_ADS_LATERAL";
export const DELETE_ADS_LATERAL = "DELETE_ADS_LATE";

